[package]
name = "gomoku_engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "gomoku"
path = "src/lib.rs"

[[bin]]
name = "gomoku"
path = "src/main.rs"

[dependencies]
eframe = "0.31"
egui = "0.31"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
